---
galaxy_info:
  role_name: nginx_multisite
  author: Migration Tool
  description: Migrated from Chef to Ansible
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags: []
